ToDo List - Javascript
MiguelArgentina/todo-list pull request #1
Opened 2021-05-29 14:40 UTC by MiguelArgentina

- ToDos are objects of Todo class
- Todos are part of  Project classes
- Objects are created dynamically 
- Todos must be created within a Project
- Todos and Projects can be deleted
- Todos information is editable
- All the information is stored in LocalStorage
- If there´s no information, the app creates a Default Project
- Bootstrap was used to style elements

2021-05-29 23:09 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well so far. Here're the major highlights of this PR:__

- You've produced a working project :+1: 
- Your linters are running/passing successfully :100: 
- Your project design interface looks nice :ok_hand: 

__However, some changes that you are required to make before moving on to the next task. Please check my comments below and fix them as appropriate.__

### **Required Changes**

- [ ] DOM-Manipulation and Logic are expected to be in separate modules (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png">screenshot</a> from <a href="https://www.theodinproject.com/courses/javascript/lessons/todo-list" rel="nofollow noreferrer noopener" target="_blank">Odin</a>). In regards to this, your `index.js` file seems pretty big due to the fact that you're having logic in there. I think you should separate the logic in this file to a separate file.
- [ ] You're having an `index.html` file inside the `src`, and another `index.html` file in the `dist` directory of this project. I'm not quite sure of the function of this file, since the main HTML file for this project should be in the `dist` folder. Is there any logical explanation for this? If there's none, I think you should remove one of the files, as one `index.html` file is advised for this project. But if there is, please let the reviewers know.
- [ ] Check the comments under the review.

### **Optional Changes**
_Every comment with the **OPTIONAL** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Validating the `New Todo` form. You should not be able to create an empty todo

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can see your comments and respond._

_**Please make the required changes and submit another review request when you are done.**_

* * *
Cheers,
**Taofeek Olalere**
__Cheers and happy coding :smiley:__

2021-05-29 23:09 UTC, teekaytech commented on src/helpers.js
> +function getProject(projectName, projectsCollection) {
**Required**
One of this project's specific requirement is to use ES6 syntax (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/es6_requirement.png">screenshot</a> from <a href="https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/" rel="nofollow noreferrer noopener" target="_blank">Pathwright</a>)
<ul data-sourcepos="89:3-92:0" class="task-list">
<li data-sourcepos="89:3-89:66" class="task-list-item">
<input type="checkbox" class="task-list-item-checkbox" disabled=""> usage of arrow functions instead of the <code>function</code> keyword</li>
</ul>


Therefore, you have to refactor all your functions to use the arrow function syntax. Please effect that change in this file and all other ones.

2021-05-29 23:09 UTC, teekaytech commented on README.md
> +
**Required**
Since you've added all the necessary packages into the `package.json` file, I think you should just tell the user to run `npm start` to use the project locally.

2021-05-31 20:17 UTC, Diegodsha commented
The index.html file in the ./src folder is the reference template that webpack uses to build either for production or development and that way we can forget about worrying if that file is deleted by any mistake or circumstance from the ./dist folder, also, since webpack build minified code for production that template its also for our understanding.

2021-05-31 21:20 UTC, umararshadbut requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @MiguelArgentina and @Diegodsha 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] Please work on the previous Code Reviewer suggestions as given in the comments.

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

2021-05-31 21:24 UTC, Diegodsha commented
> # Status: REQUIRED CHANGES warning construction
> 
> Hi @MiguelArgentina and @Diegodsha
> Good job with the changes! tada We are almost there.
> We, however, do have a few changes to carry out before we proceed.
> 
> Kindly work on the suggested changes point_down.
> 
>     * [ ]  Please work on the previous Code Reviewer suggestions as given in the comments.
> 
> 
>     * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> 
> **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
> HAPPY CODING computer
> **Umair**

Hello @umararshadbut hope you're having a great day, we've made the required changes, can you point us which ones are still missing please?

2021-05-31 23:07 UTC, taiwo2 approved these changes
# STATUS: APPROVED 🎉 
@MiguelArgentina and @Diegodsha , Weldone for implementing the requested changes Kindly merge and prepare for your next task

2021-06-01 15:17 UTC, merged